# Generated by Django 4.0.4 on 2022-05-10 18:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=254, null=True)),
                ('user_id', models.CharField(blank=True, max_length=254, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_time', models.TimeField(default=datetime.time(18, 0))),
                ('grand_total', models.IntegerField(default=0)),
            ],
        ),
    ]
