# Generated by Django 4.0.4 on 2022-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bag_bag_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_items',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
