# Generated by Django 4.0.4 on 2022-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='bag_name',
            field=models.CharField(blank=True, default='guest', max_length=254, null=True),
        ),
    ]
