# Generated by Django 4.0.4 on 2022-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bag_bag_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
