# Generated by Django 4.0.4 on 2022-06-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('Booking', 'Booking'), ('Other', 'Other')], default='Booking', max_length=15)),
                ('message', models.TextField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
