# Generated by Django 4.0.4 on 2022-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='newsletter_signup',
            field=models.BooleanField(default=True),
        ),
    ]
