# Generated by Django 4.0.4 on 2022-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
