# Generated by Django 4.0.4 on 2022-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
