# Generated by Django 4.0.4 on 2022-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newsarticle_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='showdate',
            field=models.BooleanField(default=True),
        ),
    ]
